//! Transpiler (§4.3, M5): `StateGraph` → Rust AST via `quote!`.
//!
//! The output is a complete `no_std` `cdylib` crate root that, once compiled
//! with `rustc --target wasm32-unknown-unknown -O`, produces a `gen_XXX.wasm`
//! satisfying the FFI documented in `wasm-host`:
//!
//! ```text
//!     (memory (export "memory"))
//!     (func   (export "process") (param i32 i32) (result i64))
//! ```
//!
//! ## Match-Flattening (PRD M5, mandatory)
//!
//! A naive `match node { ... match byte { ... } ... }` over a multi-thousand
//! node graph generates a single `match` arm tree large enough to push
//! `rustc`/LLVM into super-linear optimization time, blowing the WSS keepalive
//! budget on every Rebirth. Per the PRD we partition aggressively:
//!
//! 1. Edges below the EMA threshold are dropped at the source — they remain
//!    `Unmapped` and re-grow in the Ephemeral Layer if they matter.
//! 2. Each surviving source-node gets its own `step_NNNN(byte) -> i32`
//!    function whose body is a single `match byte` with at most 256 arms
//!    (one per `u8`, the natural ceiling).
//! 3. The outer `dispatch(node, byte)` is itself partitioned into chunks of
//!    `MAX_DISPATCH_ARMS` and recursed via tail-style helper dispatchers, so
//!    no single function ever holds more than `MAX_DISPATCH_ARMS` arms. This
//!    keeps each function's arm count constant and `rustc` time linear in the
//!    node count.
//!
//! `quote!` is the only AST primitive used here. It is *generative* (PRD §4.3
//! explicitly carves it out from the no-parsers rule), so the emitted source
//! is guaranteed syntactically valid before it ever reaches `rustc`,
//! drastically reducing "stillbirth" of an evolution cycle.

use ephemeral::{NodeId, StateGraph, ROOT};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::BTreeMap;

/// Max arms emitted in any single `match` (per PRD M5). 256 is the natural
/// ceiling for `match byte { .. }` and a comfortable upper bound for the
/// recursive node dispatcher as well.
pub const MAX_DISPATCH_ARMS: usize = 256;

/// Knobs for one transpile pass. Defaults match the PRD verification recipe
/// (M5 + §6) closely enough that callers usually only override `ema_threshold`.
#[derive(Debug, Clone, Copy)]
pub struct SynthesizeOptions {
    /// Edges with `score < ema_threshold` are skipped — they stay Unmapped at
    /// runtime and re-grow in the Ephemeral Layer if they matter (§6).
    pub ema_threshold: f64,
}

impl Default for SynthesizeOptions {
    fn default() -> Self {
        Self { ema_threshold: 0.0 }
    }
}

/// Transpile a `StateGraph` into a self-contained `no_std` `cdylib` crate
/// root. The returned `TokenStream` can be written verbatim to
/// `fossils/gen_XXX.rs` and handed to the incubator.
pub fn synthesize(graph: &StateGraph, opts: SynthesizeOptions) -> TokenStream {
    // Group surviving edges by source node so we can emit one step function
    // per node. `BTreeMap` keeps the output deterministic, which matters for
    // reproducible fossils (§7).
    let mut by_source: BTreeMap<NodeId, Vec<(u8, NodeId)>> = BTreeMap::new();
    for (&(from, byte), edge) in &graph.edges {
        if edge.score < opts.ema_threshold {
            continue;
        }
        by_source.entry(from).or_default().push((byte, edge.target));
    }
    // ROOT must always have a step function so `process()` can call into it
    // even on a fresh graph with no surviving edges.
    by_source.entry(ROOT).or_default();

    let step_fns = by_source
        .iter()
        .map(|(node, edges)| emit_step_fn(*node, edges))
        .collect::<Vec<_>>();

    let dispatcher = emit_dispatcher(by_source.keys().copied().collect());

    quote! {
        // ====================================================================
        // Generated by `transpiler::synthesize` — DO NOT EDIT BY HAND.
        // This file IS the fossil. The next generation will overwrite it.
        // ====================================================================
        #![no_std]
        #![no_main]
        #![allow(unused_parens, clippy::all)]

        #[panic_handler]
        fn panic(_: &core::panic::PanicInfo) -> ! {
            // Wasm has no stderr; loop forever and let the host's epoch
            // deadline (§4.2) classify this as EpochDeadline.
            loop {}
        }

        // FFI per `wasm-host` ABI:
        //   ret >= 0  → terminal NodeId
        //   ret <  0  → packed = -ret - 1; offset = packed >> 8; byte = packed & 0xFF
        #[no_mangle]
        pub extern "C" fn process(ptr: i32, len: i32) -> i64 {
            let bytes: &[u8] = unsafe {
                core::slice::from_raw_parts(ptr as *const u8, len as usize)
            };
            let mut node: u32 = 0;
            let mut offset: usize = 0;
            while offset < bytes.len() {
                let byte = bytes[offset];
                let next = dispatch(node, byte);
                if next < 0 {
                    let packed: i64 = ((offset as i64) << 8) | (byte as i64);
                    return -(packed + 1);
                }
                node = next as u32;
                offset += 1;
            }
            node as i64
        }

        #(#step_fns)*

        #dispatcher
    }
}

/// Emit `fn step_NNNN(byte: u8) -> i32` for one source node. Each arm is a
/// single `byte_literal => target,` line; the wildcard returns -1 (Unmapped).
/// Arm count is bounded by 256 by construction (one per `u8`), so this
/// function never violates `MAX_DISPATCH_ARMS`.
fn emit_step_fn(node: NodeId, edges: &[(u8, NodeId)]) -> TokenStream {
    let name = format_ident!("step_{:08x}", node);
    let arms = edges.iter().map(|(byte, target)| {
        let b = *byte;
        let t = *target as i32;
        quote! { #b => #t, }
    });
    quote! {
        #[inline]
        fn #name(byte: u8) -> i32 {
            match byte {
                #(#arms)*
                _ => -1,
            }
        }
    }
}

/// Emit `fn dispatch(node: u32, byte: u8) -> i32` partitioned into recursive
/// chunks of at most `MAX_DISPATCH_ARMS` arms each. Each leaf chunk dispatches
/// to its `step_NNNN` functions; each internal chunk dispatches to a
/// sub-dispatcher by node-id range. Unknown nodes return -1.
fn emit_dispatcher(nodes: Vec<NodeId>) -> TokenStream {
    // `nodes` comes from a BTreeMap so it's already sorted ascending.
    let helpers = build_dispatch_tree(&nodes, 0);
    let root_call = if nodes.is_empty() {
        quote! { -1 }
    } else {
        let root_name = dispatch_name(0, nodes.len());
        quote! { #root_name(node, byte) }
    };
    quote! {
        #(#helpers)*

        #[inline]
        fn dispatch(node: u32, byte: u8) -> i32 {
            #root_call
        }
    }
}

fn dispatch_name(lo: usize, hi: usize) -> proc_macro2::Ident {
    format_ident!("dispatch_{}_{}", lo, hi)
}

/// Recursively build a tree of dispatcher functions over `nodes[lo..hi]`. The
/// `offset` argument anchors helper names to absolute positions in the
/// original sorted list, so every helper has a unique stable name.
fn build_dispatch_tree(nodes: &[NodeId], offset: usize) -> Vec<TokenStream> {
    let len = nodes.len();
    if len == 0 {
        return vec![empty_dispatcher(offset, offset)];
    }
    let mut out = Vec::new();
    build_dispatch_tree_inner(nodes, offset, &mut out);
    out
}

fn build_dispatch_tree_inner(nodes: &[NodeId], offset: usize, out: &mut Vec<TokenStream>) {
    let len = nodes.len();
    let lo = offset;
    let hi = offset + len;
    let name = dispatch_name(lo, hi);

    if len <= MAX_DISPATCH_ARMS {
        // Leaf: one arm per node, dispatching to its step_NNNN.
        let arms = nodes.iter().map(|n| {
            let n_lit = *n;
            let step = format_ident!("step_{:08x}", n);
            quote! { #n_lit => #step(byte), }
        });
        out.push(quote! {
            #[inline]
            fn #name(node: u32, byte: u8) -> i32 {
                match node {
                    #(#arms)*
                    _ => -1,
                }
            }
        });
        return;
    }

    // Internal: split into MAX_DISPATCH_ARMS roughly-equal chunks and dispatch
    // by node-id range. Recurse into each chunk.
    let chunk = (len + MAX_DISPATCH_ARMS - 1) / MAX_DISPATCH_ARMS;
    let mut arms = Vec::new();
    let mut i = 0;
    while i < len {
        let j = (i + chunk).min(len);
        let sub = &nodes[i..j];
        let first = sub[0];
        let last = sub[sub.len() - 1];
        let sub_name = dispatch_name(offset + i, offset + j);
        arms.push(quote! { #first..=#last => #sub_name(node, byte), });
        build_dispatch_tree_inner(sub, offset + i, out);
        i = j;
    }
    out.push(quote! {
        #[inline]
        fn #name(node: u32, byte: u8) -> i32 {
            match node {
                #(#arms)*
                _ => -1,
            }
        }
    });
}

fn empty_dispatcher(lo: usize, hi: usize) -> TokenStream {
    let name = dispatch_name(lo, hi);
    quote! {
        #[inline]
        fn #name(_node: u32, _byte: u8) -> i32 { -1 }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn graph_with(edges: &[(NodeId, u8, NodeId, f64)]) -> StateGraph {
        let mut g = StateGraph::new();
        let max = edges.iter().map(|(_, _, t, _)| *t).max().unwrap_or(0);
        while (g.nodes.len() as NodeId) <= max {
            g.nodes.push(Default::default());
        }
        for (from, byte, target, score) in edges {
            g.edges.insert(
                (*from, *byte),
                ephemeral::Edge { target: *target, score: *score },
            );
        }
        g
    }

    #[test]
    fn empty_graph_emits_compilable_skeleton() {
        let g = StateGraph::new();
        let ts = synthesize(&g, SynthesizeOptions::default()).to_string();
        assert!(ts.contains("fn process"));
        assert!(ts.contains("fn dispatch"));
        // ROOT step is always emitted, even if its match has no arms.
        assert!(ts.contains("step_00000000"));
    }

    #[test]
    fn ema_threshold_drops_below_score_edges() {
        let g = graph_with(&[
            (ROOT, b'a', 1, 0.9),
            (ROOT, b'b', 2, 0.1),
        ]);
        let opts = SynthesizeOptions { ema_threshold: 0.5 };
        let ts = synthesize(&g, opts).to_string();
        // 'a' (0x61 = 97) survives, 'b' (0x62 = 98) is purged.
        assert!(ts.contains("97u8"));
        assert!(!ts.contains("98u8"));
    }

    #[test]
    fn one_step_fn_per_source_node() {
        let g = graph_with(&[
            (ROOT, b'h', 1, 1.0),
            (1,    b'i', 2, 1.0),
        ]);
        let ts = synthesize(&g, SynthesizeOptions::default()).to_string();
        assert!(ts.contains("step_00000000"));
        assert!(ts.contains("step_00000001"));
        // node 2 has no outgoing edges, so no step fn for it.
        assert!(!ts.contains("step_00000002"));
    }

    #[test]
    fn dispatcher_partitions_when_node_count_exceeds_limit() {
        // Build a wide graph with > MAX_DISPATCH_ARMS distinct source nodes.
        let mut g = StateGraph::new();
        for i in 0..(MAX_DISPATCH_ARMS as NodeId + 5) {
            // ensure node exists as a source
            while (g.nodes.len() as NodeId) <= i + 1 {
                g.nodes.push(Default::default());
            }
            g.edges.insert(
                (i, b'x'),
                ephemeral::Edge { target: i + 1, score: 1.0 },
            );
        }
        let ts = synthesize(&g, SynthesizeOptions::default()).to_string();
        // Root dispatcher exists and at least one sub-dispatcher was emitted
        // (proves the recursion fired, not just the leaf path).
        assert!(ts.contains("dispatch_0_"));
        let sub_count = ts.matches("fn dispatch_").count();
        assert!(sub_count >= 2, "expected recursive dispatchers, got {sub_count}");
    }
}
